### ISSUE TITLE
Font awesome shouldn't be bundeled

### ISSUE THREAD

**Issue by nabijaczleweli** [Skorezore/skorezore.github.io#1]
Rehosts are bad, Noobel plz

**Comment by nabijaczleweli** [comment]
Neither should bootstrap runtime tbh

**Comment by nabijaczleweli** [comment]
I still need to delete the folders, but I cannot do it using the web ui

**Comment by Skorezore** [comment]
I need to bundle them to make edits.

**Comment by Skorezore** [comment]
This website is an experiment, not a production one. If it were, I would have also used minified scripts.

**Comment by nabijaczleweli** [comment]
You should ***not*** edit any external libraries, ever

**Comment by Skorezore** [comment]
The library is broken in this case.

**Comment by Skorezore** [comment]
Also, careful with the absolutes. There are a handful of cases where you would want to edit external libs.
