### ISSUE TITLE
its not wurk!!!!!11!

### ISSUE THREAD

**Issue by nabijaczleweli** [skorezore/skorezore.github.io#1]
![ss](http://i.imgur.com/rxeoNKB.png)

**Comment by nabijaczleweli** [comment]
Firefox DevEd 45.0a2

**Comment by nabijaczleweli** [comment]
Fixed with newest deployment

**Comment by skorezore** [comment]
Yeah I couldn't self-close a `<script>` tag. See [this](http://stackoverflow.com/questions/69913/why-dont-self-closing-script-tags-work).
